version: "3.8"

services:
  rest:
    container_name: king-paimon-rest
    build:
      context: ./king-paimon-rest
    ports:
      - 80:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: king-paimon-postgres
    image: postgres:16.2
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=kingpaimon
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "kingpaimon", "-U", "xxx" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
