services:
    rest:
        container_name: king-paimon-rest
        build:
            context: ./king-paimon-rest
        ports:
            - 8080:8080
        networks:
            - rest-network
        depends_on:
            postgres:
                condition: service_healthy
    
    web:
        container_name: king-paimon-web
        build:
            context: ./king-paimon-web
        ports:
            - 8082:80
        networks:
            - web-network
        depends_on:
            - rest

    postgres:
        container_name: king-paimon-postgres
        image: postgres:16.2
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=xxx
            - POSTGRES_PASSWORD=xxx
            - POSTGRES_DB=kingpaimon
        ports:
            - 5432:5432
        networks:
            - rest-network
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "kingpaimon", "-U", "xxx" ]
            interval: 10s
            timeout: 5s
            retries: 5
    
    weather:
        container_name: king-paimon-weather
        build:
            context: ./king-paimon-weather
        ports:
            - 8081:8080
        networks:
            - weather-network
        depends_on:
            - mongodb

    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        volumes:
            - mongodb-data:/data/db
            - mongodb-config:/data/configdb
        ports:
            - 27017:27017
        networks:
            - weather-network

volumes:
    postgres:
    mongodb-data:
    mongodb-config:

networks:
    rest-network:
    web-network:
    weather-network:
